"""RFC-7807 Problem Details error handler."""

import http
from typing import Any

from fastapi import FastAPI, HTTPException, Request, status
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

from katibay_api.logging import logger, request_id_ctx

# Starlette renamed these two constants; resolve the spelling once here instead
# of repeating a hasattr guard at every raise site.
UNPROCESSABLE_STATUS: int = getattr(status, "HTTP_422_UNPROCESSABLE_CONTENT", 422)
CONTENT_TOO_LARGE_STATUS: int = getattr(status, "HTTP_413_CONTENT_TOO_LARGE", 413)


class ProblemDetails(BaseModel):
    """RFC-7807 Problem Details representation."""

    type: str = Field(
        default="about:blank",
        description="A URI reference that identifies the problem type.",
    )
    title: str = Field(
        ...,
        description="A short, human-readable summary of the problem type.",
    )
    status: int = Field(
        ...,
        description="The HTTP status code generated by the origin server.",
    )
    detail: str | None = Field(
        default=None,
        description=(
            "A human-readable explanation specific to this occurrence of "
            "the problem."
        ),
    )
    instance: str | None = Field(
        default=None,
        description=(
            "A URI reference that identifies the specific occurrence of " "the problem."
        ),
    )
    request_id: str | None = Field(
        default=None,
        description="Request tracking identifier.",
    )
    errors: list[dict[str, Any]] | None = Field(
        default=None,
        description="Detailed validation error list if applicable.",
    )


def create_problem_response(
    status_code: int,
    title: str,
    detail: str | None = None,
    instance: str | None = None,
    errors: list[dict[str, Any]] | None = None,
    problem_type: str = "about:blank",
    headers: dict[str, str] | None = None,
) -> JSONResponse:
    """Builds an RFC-7807 compliant JSONResponse."""
    req_id = request_id_ctx.get() or None
    problem = ProblemDetails(
        type=problem_type,
        title=title,
        status=status_code,
        detail=detail,
        instance=instance,
        request_id=req_id,
        errors=errors,
    )
    return JSONResponse(
        status_code=status_code,
        content=problem.model_dump(exclude_none=True),
        media_type="application/problem+json",
        headers=headers,
    )


def register_error_handlers(app: FastAPI) -> None:
    """Registers global RFC-7807 error handlers on the FastAPI application."""

    @app.exception_handler(HTTPException)
    async def http_exception_handler(
        request: Request, exc: HTTPException
    ) -> JSONResponse:
        title = http.HTTPStatus(exc.status_code).phrase
        detail = str(exc.detail) if exc.detail else title
        return create_problem_response(
            status_code=exc.status_code,
            title=title,
            detail=detail,
            instance=str(request.url.path),
            headers=exc.headers,
        )

    @app.exception_handler(RequestValidationError)
    async def validation_exception_handler(
        request: Request, exc: RequestValidationError
    ) -> JSONResponse:
        errors = [
            {
                "loc": [str(loc) for loc in err.get("loc", [])],
                "msg": err.get("msg", ""),
                "type": err.get("type", ""),
            }
            for err in exc.errors()
        ]
        return create_problem_response(
            status_code=UNPROCESSABLE_STATUS,
            title="Validation Error",
            detail=(
                "The request entity could not be processed due to validation " "errors."
            ),
            instance=str(request.url.path),
            errors=errors,
        )

    @app.exception_handler(Exception)
    async def unhandled_exception_handler(
        request: Request, exc: Exception
    ) -> JSONResponse:
        logger.exception("Unhandled server exception: %s", exc)
        return create_problem_response(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            title="Internal Server Error",
            detail="An unexpected error occurred. Please try again later.",
            instance=str(request.url.path),
        )
